## Hello World! My name's Ian :) 👋
# and i'm an entry level data scientist 👨‍💻 with a background in petroleum engineering![Tf2Tf2engineerGIF](https://github.com/ianbedrick007/ianbedrick007/assets/113555634/11fc3abe-4130-4202-b847-ba6612dfb01a)
. 
<!--
**ianbedrick007/ianbedrick007** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->
